# This file was generated by GoReleaser. DO NOT EDIT.
cask "sarde" do
  version "1.5.1"

  on_macos do
    on_arm do
      sha256 "57663566cf8af121ed2099da5e088499e6315ba085a181c1296cebfea82bd591"
      url "https://github.com/getsarde/sarde/releases/download/v#{version}/sarde_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "85a9859a963049b83ee117d773a302b2a8f7db918951d3743b21b404545a2e97"
      url "https://github.com/getsarde/sarde/releases/download/v#{version}/sarde_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1c22d381f8dfa4b8fa818ce7079ce5ee49dc4e70856fbe84bda00e3a66e62597"
      url "https://github.com/getsarde/sarde/releases/download/v#{version}/sarde_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "10ee240378ac60cf494816ac18de59ab56f2780225fbb19319260fc22554509b"
      url "https://github.com/getsarde/sarde/releases/download/v#{version}/sarde_linux_amd64.tar.gz"
    end
  end

  name "sarde"
  desc "A zero-config, Go-based static site generator"
  homepage "https://github.com/getsarde/sarde"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sarde"

  # No zap stanza required
end
