# This file was generated by GoReleaser. DO NOT EDIT.
cask "sarde" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "81e6b3161f7722ca76f5d8336803faac51fd13eff2b5144f733c14d270cdec0f"
      url "https://github.com/getsarde/sarde/releases/download/v#{version}/sarde_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "240b494f7761425f1cee845dda0e21317d61d06653cdbcaf60902659e1db60f5"
      url "https://github.com/getsarde/sarde/releases/download/v#{version}/sarde_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2d8bd40330a9f38c45d7398e4b3025381f10ac2a284d9adf8b5854ac92fd386b"
      url "https://github.com/getsarde/sarde/releases/download/v#{version}/sarde_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6fcb78088339057b9335a9494263fe04c76ed08e8c3955296fc599cfa051fb65"
      url "https://github.com/getsarde/sarde/releases/download/v#{version}/sarde_linux_arm64.tar.gz"
    end
  end

  name "sarde"
  desc "A zero-config, Go-based static site generator"
  homepage "https://github.com/getsarde/sarde"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sarde"

  # No zap stanza required

end
