# This file was generated by GoReleaser. DO NOT EDIT.
cask "sarde" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "563f29eaf11bd8393da15d39f1208652d4ae67bba9dc108fd36f056dc20ec731"
      url "https://github.com/getsarde/sarde/releases/download/v#{version}/sarde_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b87f3bac49dfc0b65a8e810fe41481de362716f2a4165a00cda9de463548910"
      url "https://github.com/getsarde/sarde/releases/download/v#{version}/sarde_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "24894bcbf1141d2de6542043927d3ab11f7bd97a89fe189682dd60467edad171"
      url "https://github.com/getsarde/sarde/releases/download/v#{version}/sarde_linux_amd64.tar.gz"
    end
  end

  name "sarde"
  desc "A zero-config, Go-based static site generator"
  homepage "https://github.com/getsarde/sarde"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sarde"

  # No zap stanza required

end
